meta_product_name: "Modernboxrecords"
meta_title: "Modernboxrecords - Réseau français pour la scène Rock"
meta_description: "Créez un compte sur Modern Box Records. Connectez-vous avec les acteurs utiles de la scène musicale Rock ; Artistes, Salles, Associations ou autres. Partagez vos dates de concerts, photos et  vidéos,..."
meta_image: "avatar-modern_box.jpeg"
twitter_account: "@modern_box_rec"
