# This file should contain all the #Record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#Record.create({ name: 'Single' })
#Record.create({ name: 'maxi' })
#Record.create({ name: 'Ep' })
#Record.create({ name: 'Lp' })
#Record.create({ name: 'Album' })
#  puts "      💥"

#Genre.create({ name: 'Alternative' })
#Genre.create({ name: 'British' })
#Genre.create({ name: 'Electro rock' })
#Genre.create({ name: 'Electro punk' })
#Genre.create({ name: 'Emo' })
#Genre.create({ name: 'Fonk rock' })
#Genre.create({ name: 'Garage' })
#Genre.create({ name: 'Grunge' })
#Genre.create({ name: 'Hardcore' })
#Genre.create({ name: 'Indie' })
#Genre.create({ name: 'Mathcore' })
#Genre.create({ name: 'Mathrock' })
#Genre.create({ name: 'Melodic Hardcore' })
#Genre.create({ name: 'Metalcore' })
#Genre.create({ name: 'Noise' })
#Genre.create({ name: 'Pop rock' })
#Genre.create({ name: 'Pop punk' })
#Genre.create({ name: 'Post rock' })
#Genre.create({ name: 'Post punk' })
#Genre.create({ name: 'Punk' })
#Genre.create({ name: 'Rock' })
#Genre.create({ name: 'Rock n roll' })
#Genre.create({ name: 'Sreamo' })
#Genre.create({ name: 'Stoner' })
#Genre.create({ name: 'Surf rock' })
#  puts "      💥"

#Type.create({ name: 'Concert' })
#Type.create({ name: 'Festival' })
#Type.create({ name: 'Party' })
#Type.create({ name: 'Opening' })
#Type.create({ name: 'Happening' })
#  puts "      💥"


#Activity.create({ name: 'Rehearsal' })
#Activity.create({ name: 'Music Store' })
#Activity.create({ name: 'Recordings' })
#Activity.create({ name: 'Music video making' })
#Activity.create({ name: 'Communication' })
#Activity.create({ name: 'Label' })

#  puts "      💥"

#County.create({ name: "01 - Ain" })
#County.create({ name: "02 - Aisne" })
#County.create({ name: "03 - Allier" })
#County.create({ name: "04 - Alpes-de-Haute-Provence" })
#County.create({ name: "05 - Hautes-alpes" })
#County.create({ name: "06 - Alpes-maritimes" })
#County.create({ name: "07 - Ardèche" })
#County.create({ name: "08 - Ardennes" })
#County.create({ name: "09 - Ariège" })
#County.create({ name: "10 - Aube" })
#County.create({ name: "11 - Aude" })
#County.create({ name: "12 - Aveyron" })
#County.create({ name: "13 - Bouches-du-Rhône" })
#County.create({ name: "14 - Calvados" })
#County.create({ name: "15 - Cantal" })
#County.create({ name: "16 - Charente" })
#County.create({ name: "17 - Charente-maritime" })
#County.create({ name: "18 - Cher" })
#County.create({ name: "19 - Corrèze" })
#County.create({ name: "2a - Corse-du-sud" })
#County.create({ name: "2b - Haute-Corse" })
#County.create({ name: "21 - Côte-d'Or" })
#County.create({ name: "22 - Côtes-d'Armor" })
#County.create({ name: "23 - Creuse" })
#County.create({ name: "24 - Dordogne" })
#County.create({ name: "25 - Doubs" })
#County.create({ name: "26 - Drôme" })
#County.create({ name: "27 - Eure" })
#County.create({ name: "28 - Eure-et-loir" })
#County.create({ name: "29 - Finistère" })
#County.create({ name: "30 - Gard" })
#County.create({ name: "31 - Haute-garonne" })
#County.create({ name: "32 - Gers" })
#County.create({ name: "33 - Gironde" })
#County.create({ name: "34 - Hérault" })
#County.create({ name: "35 - Ille-et-vilaine" })
#County.create({ name: "36 - Indre" })
#County.create({ name: "37 - Indre-et-loire" })
#County.create({ name: "38 - Isère" })
#County.create({ name: "39 - Jura" })
#County.create({ name: "40 - Landes" })
#County.create({ name: "41 - Loir-et-cher" })
#County.create({ name: "42 - Loire" })
#County.create({ name: "43 - Haute-loire" })
#County.create({ name: "44 - Loire-atlantique" })
#County.create({ name: "45 - Loiret" })
#County.create({ name: "46 - Lot" })
#County.create({ name: "47 - Lot-et-garonne" })
#County.create({ name: "48 - Lozère" })
#County.create({ name: "49 - Maine-et-loire" })
#County.create({ name: "50 - Manche" })
#County.create({ name: "51 - Marne" })
#County.create({ name: "52 - Haute-marne" })
#County.create({ name: "53 - Mayenne" })
#County.create({ name: "54 - Meurthe-et-moselle" })
#County.create({ name: "55 - Meuse" })
#County.create({ name: "56 - Morbihan" })
#County.create({ name: "57 - Moselle" })
#County.create({ name: "58 - Nièvre" })
#County.create({ name: "59 - Nord" })
#County.create({ name: "60 - Oise" })
#County.create({ name: "61 - Orne" })
#County.create({ name: "62 - Pas-de-calais" })
#County.create({ name: "63 - Puy-de-dôme" })
#County.create({ name: "64 - Pyrénées-atlantiques" })
#County.create({ name: "65 - Hautes-Pyrénées" })
#County.create({ name: "66 - Pyrénées-orientales" })
#County.create({ name: "67 - Bas-rhin" })
#County.create({ name: "68 - Haut-rhin" })
#County.create({ name: "69 - Rhône" })
#County.create({ name: "70 - Haute-saône" })
#County.create({ name: "71 - Saône-et-loire" })
#County.create({ name: "72 - Sarthe" })
#County.create({ name: "73 - Savoie" })
#County.create({ name: "74 - Haute-savoie" })
#County.create({ name: "75 - Paris" })
#County.create({ name: "76 - Seine-maritime" })
#County.create({ name: "77 - Seine-et-marne" })
#County.create({ name: "78 - Yvelines" })
#County.create({ name: "79 - Deux-sèvres" })
#County.create({ name: "80 - Somme" })
#County.create({ name: "81 - Tarn" })
#County.create({ name: "82 - Tarn-et-garonne" })
#County.create({ name: "83 - Var" })
#County.create({ name: "84 - Vaucluse" })
#County.create({ name: "85 - Vendée" })
#County.create({ name: "86 - Vienne" })
#County.create({ name: "87 - Haute-vienne" })
#County.create({ name: "88 - Vosges" })
#County.create({ name: "89 - Yonne" })
#County.create({ name: "90 - Territoire de belfort" })
#County.create({ name: "91 - Essonne" })
#County.create({ name: "92 - Hauts-de-seine" })
#County.create({ name: "93 - Seine-Saint-Denis" })
#County.create({ name: "94 - Val-de-marne" })
#County.create({ name: "95 - Val-d'oise" })

#  puts "      💥"

#ActivityClass.create({ name: "Very low" })
#ActivityClass.create({ name: "Low" })
#ActivityClass.create({ name: "Moderate" })
#ActivityClass.create({ name: "High" })
#ActivityClass.create({ name: "Very high" })

#  puts "      💥"


#Instrument.create({ name: "Basse 4 cordes" })
#Instrument.create({ name: "Basse 5 cordes" })
#Instrument.create({ name: "Batterie" })
#Instrument.create({ name: "Chant lead" })
#Instrument.create({ name: "Choeurs" })
#Instrument.create({ name: "Guitare 6 cordes" })
#Instrument.create({ name: "Guitare 7 cordes" })
#Instrument.create({ name: "Guitare 8 cordes" })
#Instrument.create({ name: "Keyboards" })
#Instrument.create({ name: "Lunières" })
#Instrument.create({ name: "Machines" })
#Instrument.create({ name: "Sonos" })

#puts "      💥"

